// Worker entry: the OpenNext-built app plus a cron trigger.
// @ts-ignore - generated by `opennextjs-cloudflare build`
import openNext from "./.open-next/worker.js";

interface Env {
  CRON_SECRET: string;
}

export default {
  fetch: openNext.fetch,

  // Runs the app's own background work (catalog sync, prices, FX rates) in small
  // slices: see lib/cloud-tick.ts. Goes through the app so it shares its database client.
  async scheduled(_controller: unknown, env: Env, ctx: { waitUntil(p: Promise<unknown>): void }) {
    ctx.waitUntil(
      openNext
        .fetch(
          new Request("https://cron.internal/api/cron/tick", {
            method: "POST",
            headers: { "x-cron-secret": env.CRON_SECRET },
          }),
          env,
          ctx,
        )
        .then(async (res: Response) => {
          if (!res.ok) console.error(`[cron] tick failed: ${res.status} ${await res.text()}`);
        }),
    );
  },
};
